#!/usr/bin/env ruby
#
# (C)opyright 2010 Ricardo Martins <ricardo at scarybox dot net>
# Licensed under the MIT/X11 License. See LICENSE file for license details.



if __FILE__ == $PROGRAM_NAME

end
# cursor: 6 del
